name: first workflow

on: [push] 

jobs: 

  build:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: hello friend
        run: echo "hello friend from ${{github.workflow}}"